### ISSUE TITLE
In 11.0.0-preview64 Window NativeMenu on Ubuntu Unity will not reopen after closing

### ISSUE THREAD

**Issue by RobinsonWM** [AvaloniaUI/Avalonia#10767]
**Describe the bug**
This was not a problem in `11.0.0-preview5` and appears to be a regression in `11.0.0-preview6`.
It reproduces with the sample app `ControlCatalog.NetCore`.
If a `Window` has a `NativeMenu`, click one of the top-level headers to open the menu. Close the menu by either selecting an item or clicking outside of the menu bar. The entire menu bar becomes unresponsive to inputs until the app is restarted; the menus won't open anymore. HotKeys continue to work.

I do not have a machine with Mac OS to attempt to reproduce the problem there.

**To Reproduce**

1. Install Ubuntu 22.04 with the old Unity desktop environment, which supports `NativeMenu`. (see <https://www.makeuseof.com/install-unity-desktop-ubuntu-22-04/>)
2. Build `ControlCatalog.NetCore` for Linux
3. Run `ControlCatalog.NetCore`
4. Click a menu in the `NativeMenu` to open it, for example **File**
_It opens as expected_
5. Close the menu by clicking **File** a second time
_It closes as expected_
6. Click **File** or any other menu to open it.
_It does not open_

**Expected behavior**
The user should be able to open, close, and re-open `NativeMenu`s as many times as they want.

**Screenshots**
![image](https://user-images.githubusercontent.com/7342538/227275035-b96147da-aae3-46c0-95f0-2d8262ced9a7.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04 with Unity desktop environment, running on as a Hyper-V VM on Windows 11
- Reproduced with .NET 6 and .NET 7
- Did not attempt to reproduce on Mac OS

**Comment by maxkatz6** [comment]
@affederaffe sorry for pinging, but this one also seems like related to the dbus issue. https://github.com/AvaloniaUI/Avalonia/issues/10749

**Comment by RobinsonWM** [comment]
I see that #10749 is closed now, but this problem with the NativeMenu on Ubuntu Unity is still occurring in 11.0.0-rc1.1.

**Comment by timunie** [comment]
@RobinsonWM aren't the issues different? And even if they are the same, one tracking issue (this one) is enough imo

**Comment by RobinsonWM** [comment]
From the comment on March 24, it sounded like there was some suspicion that this issue might have been a different manifestation of the same underlying issue as #10749, which was fixed by updating to a new version of the dbus dependency.
So yes, I think that confirms that the issues are different, since this issue is still happening after updating to the new version of dbus.

**Comment by affederaffe** [comment]
Can reproduce this on Unity, however, on KDE it works perfectly. There was an error caused by the source generator (see https://github.com/affederaffe/Tmds.DBus.SourceGenerator/commit/9d037e04b564d6a7c8f5de628138d338762b2337), which doesn't fix this bug though. It seems like emitting the LayoutUpdated signal causes the socket to close, I have no idea what's happening exactly though.
