### ISSUE TITLE
Brush using dynamic resource not updated in preview 6

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#11036]
**Describe the bug**
Our theming mechanism is not working as expected in Avalonia 11. It was working fine in 0.10.x. 

I was able to reproduce it in a minimal application (it works as expected for `0.10.x` but not for `preview 6`).

The way we were using the styles, is quite simple. We define the colors in style sets:
* [LightColors.xaml](https://github.com/danipen/AvaloniaCanvasTest/blob/master/AvaloniaCanvasTest/LightColors.xaml)
* [DarkColors.xaml](https://github.com/danipen/AvaloniaCanvasTest/blob/master/AvaloniaCanvasTest/DarkColors.xaml)

And then, we define the brushes ([Brushes.xaml](https://github.com/danipen/AvaloniaCanvasTest/blob/master/AvaloniaCanvasTest/Brushes.xaml)) using the colors as `DynamicResources`

To change the theme, we load the colors in the appropriate styles slot:
https://github.com/danipen/AvaloniaCanvasTest/blob/e953751576e8816b3491ec15ec5472a9965c0055/AvaloniaCanvasTest/MainWindow.axaml.cs#L27

**To Reproduce**
Open the minimal sample: https://github.com/danipen/AvaloniaCanvasTest
Click the "Change background color" button.

**Expected behavior**
The rectangle should become green (it's working as expected in `0.10.x`):
![expected](https://user-images.githubusercontent.com/501613/232424791-fd2d5123-e289-4053-a3ea-dc66b6fda890.gif)

**Actual behavior**
The rectangle background color doesn't change in the latest changes on master.
![actual](https://user-images.githubusercontent.com/501613/232424858-fbf1670e-05b7-4469-85ca-1fbfe9cf0329.gif)

**Desktop (please complete the following information):**
- OS: Windows
- Version latest master

**Additional context**
Note that we're not using the ThemeVariant or the ControlThemes yet, that probably fits better for this approach. Note that when we started our project that was not available ... we will try to upgrade to that sometime when we can.

In the meantime, if this bug can be addressed it would fix 99% percent of our current theming issues in preview 6.

**Comment by robloo** [comment]
I also still see resource issues on my end and with FluentAvalonia. This might be a key piece in fixing them.

**Comment by maxkatz6** [comment]
> Note that we're not using the ThemeVariants or the ControlThemes yet, that probably fits better for this purpose. Note that when we started our project those features were not available. We will try to upgrade to use that sometime when we can.

Yes, ideally it should be moved to ThemeVariants. And brushes should be duplicated per each ThemeDictionary to be theme aware.

Issue itself seems to be related to composition renderer media invalidation, I suppose. Needs to double check.

**Comment by maxkatz6** [comment]
Yes, adding `mCanvas.Children[0].InvalidateVisual();` in the end of ChangeBackgroundButton_Click solves the issue.

**Comment by maxkatz6** [comment]
Apparently, as per @kekekeks this rendering code by itself wouldn't work even in 0.10.x. And probably something else was invalidating there, like whole window background.

**Comment by danipen** [comment]
That's right. Forcing the components to redraw after a theme change can fix the issue... However, while we were relying on an automatic brush color update in `0.10.x`, this mechanism is no longer working as expected in `11.0.x`. As a result, we're experiencing some visual issues when changing the theme, and it's not feasible to handle the redraw for each control individually once we change the theme.

We understand that migrating to `ThemeVariant` might be a solution, but it's not an affordable task for us at this moment (our code base is huge!). So, we would really appreciate it if we could get some help to fix this issue.

As an additional note, as you can see from the attached GIF, take into account that some controls **are being updated correctly** (such buttons or text blocks), while others are not (elements inside the canvas). 
![brex](https://user-images.githubusercontent.com/501613/233005461-2c331fce-7d0f-42c4-81d4-511aa5e03fc6.gif)

Thank you for your attention to this matter.

**Comment by grokys** [comment]
Seems to have been fixed, tested in current master and the rectangle becomes green 🎂

**Comment by legistek** [comment]
Unsure if this is related or if I should open a new bug, or if it's entirely intended, but -

If I declare a `SolidColorBrush` with a `Color` value as a `DynamicResource` should I need to use `DynamicResource` whenever I reference the brush, or is `StaticResource` sufficient at that point because the target isn't actually getting a new brush value, but rather the brush itself is changing? And does the fix for this issue in master address this scenario? Thanks!

**Comment by maxkatz6** [comment]
@legistek StaticResource is sufficient when the resource itself is not changing.

**Comment by timunie** [comment]
@legistek best is to wait for the fix and if issue persists, open a new issue. Rn I think it should be covered, but you never know 100 % ;-)

**Comment by legistek** [comment]
Oh I am plenty familiar with that feeling. :). Got it thank you all!
