### ISSUE TITLE
Incorrect typesetting when blend with non-English texts

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#13166]
## Describe the bug

When the TextBlock displays the text with blended English and non-English texts, typesetting will be incorrect.

## To Reproduce

[TestRepo (https://github.com/laolarou726/TypesettingErrorDemo)](https://github.com/laolarou726/TypesettingErrorDemo)

## Expected behavior

<img width="254" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/25716486/e91d2ad4-06a1-4bf6-9b4a-bc6a11cb1cd3">

The text that has the red foreground should fill the first line of text with the rest of the Chinese texts rather than jump to a new line.

```xaml
<StackPanel Spacing="10">
    <TextBlock
        Text="The quick brown fox jumps over the lazy dog"
        HorizontalAlignment="Center"
        VerticalAlignment="Center"
        TextWrapping="Wrap"/>
    <TextBlock
        Text="一二三 The quick brown 一二三 fox jumps over the lazy dog"
        HorizontalAlignment="Center"
        VerticalAlignment="Center"
        TextWrapping="Wrap"/>
    <TextBlock
        Foreground="Red"
        Text="一二三四 TEXT 一二三四五六七八九十零"
        HorizontalAlignment="Center"
        VerticalAlignment="Center"
        TextWrapping="Wrap"/>
    <TextBlock
        Text="TEXT 一二 TEXT 三四 TEXT 一二三四五六七八九十零"
        HorizontalAlignment="Center"
        VerticalAlignment="Center"
        TextWrapping="Wrap"/>
</StackPanel>
```

## Environment 

- OS: Windows 11 22H2
- Avalonia-Version: 11.0.4

**Comment by comesx4** [comment]
The behavior of Chinese line wrapping is not consistent with that in WPF. In WPF, line wrapping can be done between any Chinese characters.

**Comment by timunie** [comment]
Probably worth to check nightly builds or at least 11.0.5 as we have some text fixes inside.

**Comment by laolarou726** [comment]
> Probably worth to check nightly builds or at least 11.0.5 as we have some text fixes inside.

Just tried the latest nightly build (11.1.999-cibuild0040550-beta), and the problem is still present:
<img width="269" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/25716486/9930c090-a35a-4b69-b108-4feeb495372e">

**Comment by robloo** [comment]
Note that line wrapping doesn't work properly for English texts either at certain display scales.

Tooltip should be "Sea Green"
![image](https://github.com/AvaloniaUI/Avalonia/assets/17993847/6f37b98d-a2d7-41cb-b5ba-1cdec0a0d703)

Should be "Salmon" but I guess this is a bigger problem than wrapping in this case
![image](https://github.com/AvaloniaUI/Avalonia/assets/17993847/e339b2b8-47de-417e-b737-61b3b62fa1d1)

Yes, I mention this from time to time to note that text measurement still has some issues buried some place (was briefly solved in one of the previews though). I'm only mentioning it here because it might be related.

**Comment by laolarou726** [comment]
> Note that line wrapping doesn't work properly for English texts either at certain display scales.
> 
> Tooltip should be "Sea Green" ![image](https://user-images.githubusercontent.com/17993847/273479306-6f37b98d-a2d7-41cb-b5ba-1cdec0a0d703.png)
> 
> Should be "Salmon" but I guess this is a bigger problem than wrapping in this case ![image](https://user-images.githubusercontent.com/17993847/273479329-e339b2b8-47de-417e-b737-61b3b62fa1d1.png)
> 
> Yes, I mention this from time to time to note that text measurement still has some issues buried some place (was briefly solved in one of the previews though). I'm only mentioning it here because it might be related.

@Gillibald @timunie 

Just did another test using the SegoeIcons font. Also getting the incorrect result:

Under Avalonia:
<img width="250" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/25716486/0049acdb-e55f-47e6-9e96-ce6f1e2606b5">

Under WPF:
<img width="230" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/25716486/581b851c-c0f2-4de5-9ebc-be727336f662">

Here is the repro for both Avalonia and WPF:
[https://github.com/laolarou726/TypesettingErrorDemo](https://github.com/laolarou726/TypesettingErrorDemo)
[https://github.com/laolarou726/TypesettingErrorDemoWPF](https://github.com/laolarou726/TypesettingErrorDemoWPF)

**Comment by laolarou726** [comment]
@Gillibald I just tested both the latest PreBuild Avalonia (11.1.999-cibuild0040790-beta) and 11.0.999-cibuild0040632-beta. It seems the problem still present:
<img width="236" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/25716486/194283bc-e9a4-4873-b3f0-0627135e2e3e">

**Comment by timunie** [comment]
Can you please share the sample shown using the PR as current nuget version?

**Comment by laolarou726** [comment]
> Can you please share the sample shown using the PR as current nuget version?

Just updated the Nuget version, the problem still present.

[https://github.com/laolarou726/TypesettingErrorDemo](https://github.com/laolarou726/TypesettingErrorDemo)

Could you please reopen this issue? Thx.

**Comment by laolarou726** [comment]
> Can you please share the sample shown using the PR as current nuget version?

Just updated to the latest night, this issue was fixed, sorry for the confusing! However, the problem when using the icon font is still present, could you please double check that? Thanks.

Here is the repo: [https://github.com/laolarou726/TypesettingErrorDemo](https://github.com/laolarou726/TypesettingErrorDemo) See *latest-nightly* branch

<img width="266" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/25716486/89dfd7ec-974e-4ff0-8c31-ca6ff840aaa6">

**Comment by timunie** [comment]
I think that should be a separate issue

**Comment by laolarou726** [comment]
> I think that should be a separate issue

Sure. Here is the new issue: [#13235](https://github.com/AvaloniaUI/Avalonia/issues/13235)
