### ISSUE TITLE
DataGrid can not show row data in "Browser" project in 11.1.0-beta1

### ISSUE THREAD

**Issue by ismlsmile** [AvaloniaUI/Avalonia#14991]
### Describe the bug

some key points:
1. This is not a common coding style, but it should be a legal coding style. I am not using a ViewModel, I am using View as a ViewModel.
2. It works well in 11.0.x
3. In 11.1.0-beta1, "Desktop" project is still ok, but "Browser" project failed. DataGrid can not show row data.

### To Reproduce

Here is the demo project:
[DataGridDemo.zip](https://github.com/AvaloniaUI/Avalonia/files/14611459/DataGridDemo.zip)

### Avalonia version

11.1.0-beta1

### OS

WebAssembly

**Comment by timunie** [comment]
@ismlsmile could you test latest nightly? We had some AOT issues which should be resolved in nightly and being available in 11.1.0-beta2

**Comment by ismlsmile** [comment]
I am sorry I could not find any nightly package on nuget. Should I checkout the source code and compile by myself?

**Comment by timunie** [comment]
https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

**Comment by ismlsmile** [comment]
tested with 11.2.999-cibuild0046219-beta, this bug still exists

**Comment by johanpolson** [comment]
I was able to get the code to work by adding `, Mode=OneTime` to the `ItemsSource="{Binding People}"`
it can be a clue to what is going wrong.

I could also see that after "DataContext" was assigned in Ctor,
`InpcPropertyAccessor.SendCurrentValue()` was called twice.
but in the second invocation of `InpcPropertyAccessor.SendCurrentValue()` a Exception is thrown on the line `var value = Value;` in `InpcPropertyAccessor.SendCurrentValue()` .

```
System.InvalidCastException: Specified cast is not valid.
   at CompiledAvaloniaXaml.XamlIlHelpers.ControlCatalog.MainView,ControlCatalog.HelloMega!Getter(Object )
   at Avalonia.Data.Core.ClrPropertyInfo.Get(Object target) in C:\repo\Avalonia\src\Avalonia.Base\Data\Core\ClrPropertyInfo.cs:line 27
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.InpcPropertyAccessor.get_Value() in C:\repo\Avalonia\src\Markup\Avalonia.Markup.Xaml\MarkupExtensions\CompiledBindings\PropertyInfoAccessorFactory.cs:line 88
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.InpcPropertyAccessor.SendCurrentValue() in C:\repo\Avalonia\src\Markup\Avalonia.Markup.Xaml\MarkupExtensions\CompiledBindings\PropertyInfoAccessorFactory.cs:line 132
```

Hope this can be help !

**Comment by johanpolson** [comment]
@ismlsmile in your sample code, you first set the DataContext to the MainView in the MainView ctor:
``` C#
DataContext = this;
```
but then after that u set DataContext of MainView to a new MainViewModel in App.axaml.cs
``` C#
desktop.MainWindow = new MainWindow
{
   DataContext = new MainViewModel()
};
```
Just edit the code in App.axaml.cs and then it works !

**Comment by timunie** [comment]
@ismlsmile can you double-check the suggested change from @johanpolson ? I think that may be the root cause here. If that's the case, this is by design. Set DataContext only once please.

**Comment by ismlsmile** [comment]
I delete the code "DataContext = new MainViewModel()" in App.axaml.cs, but it still does not work in Browser.
The original sample code really Set DataContext twice. But my question is:
1. why it could work in Desktop in 11.1.0-beta1?
2. why it could all work in 11.0.x

It seems that the same code do not keep the same behavior in different platform.

**Comment by timunie** [comment]
true, Browser and Desktop should either both work or both fail. -- reopened

**Comment by parko65** [comment]
I'm experiencing same behaviour in 11.0.10.
