### ISSUE TITLE
WindowState does not reflect correct state on Windows

### ISSUE THREAD

**Issue by fitdev** [AvaloniaUI/Avalonia#16307]
### Describe the bug

`Window.WindowState` property seems to only remember programmatically set values, but when the actual window state changes afterwards, such as when user minimizes/maximizes the window, the property value remains unchanged (still stuck on the last programmatically set value). Moreover OnPropertryChanged is not being raised for when window state actually changes.

### To Reproduce

Just monitor the value of `Window.WindowState` property while minimizing/maximizing/restoring window.

### Expected behavior

Reading `Window.WindowState` should always accurately reflect the actual state.
When the state changes - for whatever reason - whether programmatically or via OS/chrome interaction, OnPropertyChanged for WindowState property should be raised.

### Avalonia version

11.1 RC2

### OS

Windows

### Additional context

Likely related to #16227

Unfortunately `PlatformImpl.WindowState` which looks like it would return correct value is not accessible as it is internal.

**Comment by emmauss** [comment]
This is fixed as of master. Could you confirm with the latest commit.

**Comment by timunie** [comment]
https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

Here is how to test it. We cannot modify already released versions.

**Comment by fitdev** [comment]
If the fix is in the nightly, when will it make its way to official release - 11.1 or 12?

**Comment by fitdev** [comment]
Tried latest nightly - 11.1.999 - No, the issue remains! Window is effectively normal, but Window.State reports it as maximized still. It basically bypasses the actual window state check and uses some sort of cached value, which has not been properly updated.

**Comment by timunie** [comment]
11.1.999 is outdated nightly. Check your nuget feed sources and make sure to enable preview checkmark. Should be 11.2.999

**Comment by fitdev** [comment]
Yeah, sorry not sure how I picked up the wrong version. 
As of 11.2.999-cibuild0050204-alpha the issue seems fixed.
But so it won't make it into 11.1 RTM?

**Comment by timunie** [comment]
Not sure it's making it into 11.1.1 probably but can't confirm. If you're a paying customer you can request it.
