### ISSUE TITLE
System.InvalidOperationException: Could not create glyphTypeface on Linux after upgrade to version 11.1.x

### ISSUE THREAD

**Issue by sandsc** [AvaloniaUI/Avalonia#16612]
### Describe the bug

Gets InvalidOperation while app startup,  It works on 11.0.x version.
```
System.InvalidOperationException: Could not create glyphTypeface. Font family: $Default (key: ). Style: Normal. Weight: Normal. Stretch: Normal
   at Avalonia.Media.Typeface.get_GlyphTypeface()
   at Avalonia.Rendering.Composition.Compositor.get_DiagnosticTextRenderer()
   at Avalonia.Rendering.Composition.Compositor.CreateCompositionTarget(Func`1 surfaces)
   at Avalonia.Rendering.Composition.CompositingRenderer..ctor(IRenderRoot root, Compositor compositor, Func`1 surfaces)
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl)
   at Avalonia.Controls.Window..ctor(IWindowImpl impl)
   at Avalonia.Controls.Window..ctor()
```

### To Reproduce

Create a default Avalonia app using Project template by using version 11.1.x, run it on linux, e.c.  ubuntu or kylinOS v10.

### Expected behavior

The app starts normally

### Avalonia version

11.1.x

### OS

Linux

**Comment by lindexi** [comment]
@sandsc You should add the font options in Kylin os:


```csharp
        appBuilder.With(new FontManagerOptions()
        {
            DefaultFamilyName = "Noto Sans CJK SC",
            FontFallbacks =
            [
                new FontFallback { FontFamily = "文泉驿正黑" },
                new FontFallback { FontFamily = "DejaVu Sans" },
            ],
        });
```

I wrote the Chinese blog in https://blog.lindexi.com/post/dotnet-%E8%A7%A3%E5%86%B3-Avalonia-%E5%9C%A8-OpenKylin-%E9%BA%92%E9%BA%9F%E7%B3%BB%E7%BB%9F%E8%BF%90%E8%A1%8C%E6%89%BE%E4%B8%8D%E5%88%B0%E9%BB%98%E8%AE%A4%E5%AD%97%E4%BD%93%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5.html

**Comment by sandsc** [comment]
> @sandsc You should add the font options in Kylin os:
> 
> ```cs
>         appBuilder.With(new FontManagerOptions()
>         {
>             DefaultFamilyName = "Noto Sans CJK SC",
>             FontFallbacks =
>             [
>                 new FontFallback { FontFamily = "文泉驿正黑" },
>                 new FontFallback { FontFamily = "DejaVu Sans" },
>             ],
>         });
> ```
> 
> I wrote the Chinese blog in https://blog.lindexi.com/post/dotnet-%E8%A7%A3%E5%86%B3-Avalonia-%E5%9C%A8-OpenKylin-%E9%BA%92%E9%BA%9F%E7%B3%BB%E7%BB%9F%E8%BF%90%E8%A1%8C%E6%89%BE%E4%B8%8D%E5%88%B0%E9%BB%98%E8%AE%A4%E5%AD%97%E4%BD%93%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5.html

Thanks, I fixed this for now by using your method, but v11.0.x doesn't have this issue, so is this an API change or a bug?

**Comment by Gillibald** [comment]
If it worked before it should still work with newer Avalonia. Buy in the end there is nothing we can do if the FontManager isn't providing a default.

**Comment by a6754z** [comment]
This is indeed a bug but the above workaround works.

**Comment by slackerbob** [comment]
This is still a bug on the newest 11.1.x release and should not be closed.

**Comment by Orange-Icepop** [comment]
The issue still exists in the latest version 11.3.7 ......
Can I use my custom font that is compiled into the application? This possibly prevents any problem.

**Comment by LegendTheDeveloper** [comment]
This issue still happening in the latest version of Avalonia 11.3.11
To get the error, you have to compile the application in Linux, and then run it on Windows

**Comment by miyou379** [comment]
I've encountered the same problem when using ilspy prebuilt release.

The variable fonts support of Avalonia is poor now. When LC=zh_CN.UTF-8, it's likely that your default font like Noto Sans CJK is a TTC variable font file, then it will fallback to other fonts (which are not variable, often something that is pure English font like `Inter`). This fallback method eventually causes the exception.

Workaround:
Modify the `Exec` section of your desktop file to
```
env LC_ALL=C.UTF-8 LANG=C.UTF-8 LANGUAGE=en_US:en <avalonia_programs>
```
or
```
env LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US:en <avalonia_programs>
```
this workaround will force avalonia programs to use English interface.
