### ISSUE TITLE
11.2+ : Binding of ItemsSource in a UserControl children is broken if the DataContext isn't explicitly set in the UserControl

### ISSUE THREAD

**Issue by Whiletru3** [AvaloniaUI/Avalonia#17744]
### Describe the bug

In Avalonia 11.2+, there are some regression regarding the DataContext in UserControl.
When the DataContext of a UserControl is heritated, if a child control is an ItemsControl, the ItemsSource binding remain null.

### To Reproduce

Using this example (just put it in the sample folder of avalonia and add it in the solution), as is in 11.1.x you can see 20 images (with random different sizes) with one red recrangle in it like this : 
![image](https://github.com/user-attachments/assets/1124cc81-f374-4ffb-9651-85875a47ddbe)

When imported in 11.2 (here in 11.2.2), 
![image](https://github.com/user-attachments/assets/054807e6-7a32-4d53-ac1d-64f1e6c55d07)

The ItemSource of the ListBox is null

In the sample, if you set the DataContext explicitly in the SingleScrollingViewerPanel (the UserControl), it brings back the images 

```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:model="clr-namespace:VirtualizationImagesWithEvents.ViewModels"
             xmlns:virtualizationImagesWithEvents="clr-namespace:VirtualizationImagesWithEvents"
             xmlns:layout="clr-namespace:VirtualizationImagesWithEvents.Layout"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="VirtualizationImagesWithEvents.SingleScrollingViewerPanel"
             x:DataType="model:MainWindowViewModel"
             x:CompileBindings="True"
             
             >
  <!--todo put this DataContextBinding in the UserControl
  DataContext="{Binding (model:ViewModelLocator).MainWindowViewModel, Source={StaticResource ViewModelLocator}}"
  -->
  <!--The DataContext of the UserControl need to be set otherwise the listbox ItemsSource will remain null-->
```

BUT not yet the rectangles.
For the rectangles, in the same file, we need to set the DataContext of the LayoutControl and use an ugly trick (a member of the PageviewModel returning this) or remove the original Binding to point :

```
 // This PageSource (pointing to this) is used only to be able to trigger the DataContext binding
 public PageViewModel PageSource
 {
     get
     {
         return this;
     }
 }
```

```
 <layout:LayoutControl x:Name="ctlLayout"
                             HorizontalAlignment="Center"
                             VerticalAlignment="Top"
                             x:DataType="model:PageViewModel"
                             DataContext="{Binding .}"
                             >
   <!--todo put this DataContextBinding in the LayoutControl
       DataContext="{Binding PageSource }"
   -->
   <!--Here we need to re set the DataContext of the control to a member (pointing to the same object this), otherwise the ItemsControl ItemsSource will stay null, or remove the original binding to point-->
 </layout:LayoutControl>
```

This is a blocker issue for us to go in 11.2+ :-(

Here is the package to reproduce :
[VirtualizationImagesWithEvents.zip](https://github.com/user-attachments/files/18082255/VirtualizationImagesWithEvents.zip)

### Expected behavior

As the Datacontext id Inherited, the listbox shouldn't be empty and the LayoutControl for each page as well. The behavior should be the same as in 11.1.3

### Avalonia version

11.2.1 11.2.2

### OS

Windows, macOS

**Comment by ShadowMarker789** [comment]
![image](https://github.com/user-attachments/assets/81537a49-9746-458b-b3c0-8712b9aeff3e)

Removing `DataContext="{Binding ., Mode=OneWay}` from your project makes it work. 

![image](https://github.com/user-attachments/assets/0657d74b-d34f-41c9-85e5-c75e9cbe442d)

If DataContext is inherited, there's no need to set it via a binding.

**Comment by nsrahmad** [comment]
Hi, 
I also encountered this bug on a feed reader app (not public) I wrote. However, I postponed reporting it because I failed to make a minimal reproduction, and assumed I must be doing something wrong (which might be the case after all).

This is how it looks on avalonia `11.1.4`:
![Screenshot 2024-12-11 114231](https://github.com/user-attachments/assets/a78675f9-99ff-4d5d-a4af-55603517a358)

Trying to upgrade to 11.2.2, without any other change to code:
![Screenshot 2024-12-11 114705](https://github.com/user-attachments/assets/0c97baad-d903-4dff-bc12-2504e3b42691)

**Comment by ShadowMarker789** [comment]
> Hi, I also encountered this bug on a feed reader app (not public) I wrote. However, I postponed reporting it because I failed to make a minimal reproduction, and assumed I must be doing something wrong (which might be the case after all).
> 
> This is how it looks on avalonia `11.1.4`: 
> 
> Trying to upgrade to 11.2.2, without any other change to code: 

Are you also using a binding on the DataContext itself? 

I haven't seen any defined behaviour of what it means to bind a data-context like this. I don't even have a conceptualization of what ought to be expected when you attempt to bind that which changes the meaning of what things point to on bindings. 

So, I would perhaps recommend not doing this and not relying on that kind of behaviour. 

Can any of y'all find documentation on what the intended behaviour is for Binding a DataContext property?

**Comment by nsrahmad** [comment]
No, I am not doing anything with `DataContext`. The previewer is rendering the contorls correctly, yet it is blank when I run it:

![Screenshot 2024-12-11 122824](https://github.com/user-attachments/assets/4fc16c39-d1c7-4f9c-b3c7-4a67e7204c67)

----
![Screenshot 2024-12-11 122940](https://github.com/user-attachments/assets/e46ede81-de2b-4aa9-b0e7-a608e9abc45a)

**Comment by ShadowMarker789** [comment]
> No, I am not doing anything with `DataContext`. The previewer is rendering the contorls correctly, yet it is blank when I run it. 

If we can get a minimal (as small as one could possibly get) reproduction, then we can get this fixed.

**Comment by Whiletru3** [comment]
> > Hi, I also encountered this bug on a feed reader app (not public) I wrote. However, I postponed reporting it because I failed to make a minimal reproduction, and assumed I must be doing something wrong (which might be the case after all).
> > This is how it looks on avalonia `11.1.4`:
> > Trying to upgrade to 11.2.2, without any other change to code:
> 
> Are you also using a binding on the DataContext itself?
> 
> I haven't seen any defined behaviour of what it means to bind a data-context like this. I don't even have a conceptualization of what ought to be expected when you attempt to bind that which changes the meaning of what things point to on bindings.
> 
> So, I would perhaps recommend not doing this and not relying on that kind of behaviour.
> 
> Can any of y'all find documentation on what the intended behaviour is for Binding a DataContext property?

The binding on itself {Binding .} or {Binding} is commonly use in xaml wpf and even in avalonia repository.
We have a workaround yes, but still it is a regression in Avalonia 11.2+.
It was really hard to reproduce it in avalonia and point this Binding. 
I'll try to create an even smaller sample.

**Comment by MrJul** [comment]
Could you please try the build from this PR: https://github.com/AvaloniaUI/Avalonia/pull/17683? It should solve the issue.

**Comment by nsrahmad** [comment]
Yay! Thnak you @MrJul. I tried #17683 and This indeed fixes this particular issue for me.

**Comment by Whiletru3** [comment]
[AvaloniaListBoxDemo.zip](https://github.com/user-attachments/files/18094731/AvaloniaListBoxDemo.zip)

**Comment by ShadowMarker789** [comment]
Okay, I'm reproducing it now. 

Yes, I can confirm that the grid is necessary to replicate the issue. 

I'm using an even simpler model and data-context, just showing a list of strings. 

```xml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             x:Class="ControlCatalog.Debugging.Issue1744"
             xmlns:local="clr-namespace:ControlCatalog.Debugging;assembly=ControlCatalog"
             xmlns:system="clr-namespace:System;assembly=System.Runtime"
             x:DataType="local:Issue17744DataContext"
             x:CompileBindings="True"
             >
  <Grid>
    <ListBox DataContext="{Binding Path=., Mode=OneWay}" ItemsSource="{Binding Path=Items}" >
      <ListBox.DataTemplates>
        <DataTemplate DataType="system:String">
          <TextBlock Text="{Binding}"/>
        </DataTemplate>
      </ListBox.DataTemplates>
    </ListBox>
  </Grid>
</UserControl>
```

**Comment by ShadowMarker789** [comment]
Further investigation... 

![image](https://github.com/user-attachments/assets/3f8f52b2-21f1-4f92-8565-1f19e558012d)

As soon as `Value` here is set (line before current) the DataContext of the ListBox is non-null. 

![image](https://github.com/user-attachments/assets/cd83a5d3-df52-4fc5-ab4d-2e05ee9b4805)

So we have a state now where the EffectiveValue of a property has been modified but no value-change notification has been sent or evented.

**Comment by ShadowMarker789** [comment]
@Whiletru3 @ can you try my attempted fix in 

https://github.com/AvaloniaUI/Avalonia/pull/17755

And confirm whether or this this appropriately addresses your issue?

**Comment by Whiletru3** [comment]
@ShadowMarker789 : you mention in your PR some test failures. Do I need to test it anyway ?

**Comment by ShadowMarker789** [comment]
> @ShadowMarker789 : you mention in your PR some test failures. Do I need to test it anyway ?

Those have been addressed. Those were unit-tests that were helpful in making sure I did not break functionality elsewhere. 

Please test when you can.

**Comment by Whiletru3** [comment]
@ShadowMarker789 : I'll test it next monday, can't do it sooner :-/

**Comment by Whiletru3** [comment]
Hello @ShadowMarker789, 

I just test the PR (cloning your repo and branch) in my sample [AvaloniaListBoxDemo.zip](https://github.com/user-attachments/files/18094731/AvaloniaListBoxDemo.zip) (as is without modification), and the issue is still there.

There are no Item in the ListBox

Also in my original Sample [VirtualizationImagesWithEvents.zip](https://github.com/user-attachments/files/18082255/VirtualizationImagesWithEvents.zip) 

No images (in the listbox) and no red rectangle (in the ItemsColtrol)

And tried in my real App (using the CI nuget), the issue still there

Did you applied some modification in the samples to get it worked ?

**Comment by ShadowMarker789** [comment]
> Did you applied some modification in the samples to get it worked ?

I must have, because after redownloading and retesting I'm now getting a blank screen same as you. 

Looking into it more now... 

On the first time the DataContext is set, the Inheritance Children of the MainWindow's DataContext property is null/none. 

Which is interesting. And partially explains why I saw different behaviours when I assigned the datacontext before loading the xaml and after loading the xaml. 

![image](https://github.com/user-attachments/assets/c195d485-8ee3-41e6-a9d0-8bed2fd832d3)
^^ The first round of notifications of the data-context being assigned, with zero children inheriting the data-context ^^ 

But then after your control (the virtualizationImages:SingleScrollingViewerPanel) joins the logical tree, there's a second round of property changed notifications going through, but it stops abruptly. 

![image](https://github.com/user-attachments/assets/0ef292dc-6d12-4bdd-8361-8571e775867d)
^^ Second round, the Effective Value of the DataContext has not changed, the system asserts.  ^^ 

And then finally, notification does not traverse the tree, leading to the strange state where the effective value of the list's data-context is correct, but the items-source is incorrect. 

![image](https://github.com/user-attachments/assets/0e4a56d0-818e-4979-a9ed-5bc953ed477e)

I'm still yet to pin down EXACTLY what the minimum steps to reproduce this is. I thought I had it before, but you are perfectly correct, my pull request does not resolve the issue.

**Comment by ShadowMarker789** [comment]
If nothing else, I finally have a failing unit-test. 

Should help in getting a fix for this shortly. 

![image](https://github.com/user-attachments/assets/a2097758-c4a6-4c42-8442-17bd9d9571e2)

**Comment by ShadowMarker789** [comment]
@Whiletru3 - can you check out latest Avalonia Master Branch and repeat your testing? I had some unit-tests that were failing on an older version of the master branch, but they are now passing in the master branch. 

When I redownload and relink your project with the Avalonia source latest master I get the following. 

![image](https://github.com/user-attachments/assets/42a6fdeb-2592-49cb-91e1-87774d404dde)

Is this the issue fixed? Can you confirm fixed on your end?

**Comment by Whiletru3** [comment]
@ShadowMarker789 Hello, thanks for all :) Indeed the issue is fixed in 11.2.3 release :)
