### ISSUE TITLE
TextBox with TextWrapping enabled is extremely buggy on Android

### ISSUE THREAD

**Issue by The-Zenix** [AvaloniaUI/Avalonia#20232]
### Describe the bug

Hi,

I've run into numerous issues using TextBox's on Android, with TextWrapping set to TextWrapping.Wrap.

Issues include:

Duplicate characters being entered after a new line.
Entire lines of text being randomly copy and pasted.
Cursor jumping to new locations when typing.
Cursor jumping to new locations when pressing backspace.

### To Reproduce

These are all pretty easy to reproduce, though I don't have the steps down 100%.

All of these were tested on a brand new app, with a single UserControl.

public class MainView : UserControl
{
    TextBox _editor;

    public MainView()
    {
        Content = BuildContent();
    }

    Control BuildContent()
    {
        var root = new StackPanel
        {
            Margin = new Thickness(20),
            Spacing = 10
        };

        _editor = new TextBox
        {
            AcceptsReturn = true,
            TextWrapping = TextWrapping.Wrap,
            HorizontalAlignment = HorizontalAlignment.Stretch,
            Height = 200,
            Text = "Type here..."
        };

        root.Children.Add(_editor);

        return root;
    }
}

For 'duplicate characters after new line', just type in text until you get to the edge of the screen. Then make sure that the very last letter of the line, the one that causes the cursor to move to the next line, is a 'space' character. After that type two letters, for example 'a' and 'b'. The 'a' will appear fine, but when you press 'b', a second 'a' will first be inserted, so the resulting text is 'aab'. This will happen consistently. You can then delete the aab and retype any two letters, the first one will always be entered twice.

For the backspace bug, just fill out the TextBox with a few lines of text. Then hold backspace. It will start off deleting ok, but then the cursor will jump backwards into some other part of the text, and it will continue deleting from there.

For the other two issues, I don't have a confirmed repro steps yet.

### Expected behavior

TextBox behaves appropriately.

### Avalonia version

11.3.6, 11.3.9

### OS

Android

### Additional context

I'm testing on a Samsung Galaxy S22, Android v16, One UI v8.0

**Comment by timunie** [comment]
Would be interesting to see if upcoming v12 helps here. You could test nightly builds with your setup if you are interested in.

**Comment by SitronX** [comment]
@timunie 

I am currently on 12.0.999 - cibuild0060243 

I noticed that the character duplication is fixed, it no longer happens.

The backspace deletion is still the issue though. If there is a multiline text and you hold backspace, when it changes the line, it randomly jumps somewhere.

**And another issue, that pains me the most** : When you have multiline text, if you for example decide you want to edit some line which is in middle, you place cursor there and start writing. When you write text and it reaches next line, the cursor always jumps somewhere else and if you keep writing, the characters get added to that random text area. Which is a major issue, because i sometimes dont notice it and the text is nonsense after that.

I find this as really major issue on android right now, TextBox is very crucial component. 

_My phone: Samsung Galaxy A54_

**Comment by SitronX** [comment]
The issue is still present in 12.0.0 release

https://github.com/user-attachments/assets/4deddcf7-c87e-4d21-b174-7d9ebf4cf58d

**Comment by AlexSCcon** [comment]
I have the exact same problem is this. Textboxes are very glitchy with text being placed at random intervals and backspacing sometimes causing the caret to jump an extra line above.

**Comment by IanRawley** [comment]
Still getting this here.  Especially when editing the middle of multi line wrapped text having the cursor jump to the last line.

**Comment by AlexSCcon** [comment]
This is still an issue on 12.0.5. I was able to somewhat get it working using #20890 which fixed all the caret issues, though it resulted in other oddities, which where more grapphical than affecting the use.
