### ISSUE TITLE
Transparent Window Background

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#2306]
Hey,

I get black background whenever I use Transparent background on any platform.
I've seen some other issues about this and it seems like it's fixed on issue #1687
![image](https://user-images.githubusercontent.com/27368554/52868101-1835d480-314b-11e9-8195-b8f97db20eed.png)
`<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="AvaloniaApplication1" Background="Transparent">`

Thanks

**Comment by kekekeks** [comment]
Should work with X11 backend. On OSX and Windows transparency isn't supported yet.

**Comment by adirh3** [comment]
Are there any plans to support transparency on Windows/OSX?
Thanks

**Comment by danwalmsley** [comment]
Of course, and PRs always welcome ;)

**Comment by kekekeks** [comment]
On Linux we've got transparency completely for free: you just use an ARGB visual and it just works. On OSX it should also be [relatively easy](https://developer.apple.com/documentation/appkit/nswindow/1419086-opaque?language=objc).

In case of Windows it's really complicated. 

There is an old API UpdateLayeredWindow which was originally meant for mouse cursor shadows. It doesn't support DirectX rendering and even with software rendering it's way slower than the usual SetDIBitsToDevice. That's the only way to have window transparency when DWM is disabled. Which is the case for Win7 systems with Aero disabled. Unfortunately, the people who are using the "classic" theme are usually very vocal about applications not supporting their config, so we can't just ignore them [until 2023](https://www.engadget.com/2018/09/09/windows-7-enterprise-support-until-2023/) .

Since Win8 DWM is always enabled, so we should be able to use DwmExtendFrameIntoClientArea and/or DwmEnableBlurBehindWindow. The problem here is that window won't be completely transparent, but have usual blurred semi-transparent background extended to the client area. I'm not sure if it's even possible to make a completely transparent (i. e. without glass or acrylic background) window without a severe performance hit.

**Comment by Splitwirez** [comment]
> 
> 
> Since Win8 DWM is always enabled, so we should be able to use DwmExtendFrameIntoClientArea and/or DwmEnableBlurBehindWindow. The problem here is that window won't be completely transparent, but have usual blurred semi-transparent background extended to the client area. I'm not sure if it's even possible to make a completely transparent (i. e. without glass or acrylic background) window without a severe performance hit.

Actually, Windows 8 also changed the behaviour of those APIs to produce opaque solid colour instead of blur. The exact colour is determined by the user's current theme settings.

**Comment by jtbrower** [comment]
### +1 for Window Transparency in Windows.

Window transparency seems to be a tough issue to solve as I ran into the same problem with WinUI 3.0.  

In WPF I typically make my Windows completely look-less and force the Windows Templated Content to define how the window looks.

With WinUI 3.0 I spent quite a bit of time trying to find a work-around, but after asking one of their team members, I was told it was not possible to achieve what I wanted to do.

I am guessing this is one of those features that only we multiple Window app WPF developers needs and this is a low priority.  Has anyone found a workaround?

**Comment by grokys** [comment]
@danwalmsley shouldn't this issue have been addressed now? I though your recent changes would have implemented this?

**Comment by Splitwirez** [comment]
> @danwalmsley shouldn't this issue have been addressed now? I though your recent changes would have implemented this?

I can verify from experience (and from having brought the functionality in question to Windows 8.1) that it has been addressed. Not 100% comprehensively (e.g. Windows 7 and Windows without DWM users still get opaque black backgrounds instead), but it has more or less been addressed.




> In WPF I typically make my Windows completely look-less and force the Windows Templated Content to define how the window looks.

As a former WPF app developer, I can 100% relate to that. CSDs can really help your app stand out, and sometimes even have functional benefits too. A word of warning though, from my experience learning the ways of Avalonia: DO NOT enforce the use of your custom decorations. Give your users the option to disable them, even if it's to their own detriment. Failure to do so will have many Linux users loathing your existence to no end (and potentially some from other platforms as well, depending on how poorly you've implemented your custom decorations).

**Comment by FrankenApps** [comment]
`WindowTransparencyLevelHint="Transparent"` is needed, too.

**Comment by grokys** [comment]
OK - we still need documentation about this I think but I think we can close this issue!

**Comment by jtbrower** [comment]
> A word of warning though, from my experience learning the ways of Avalonia: DO NOT enforce the use of your custom decorations.

@Splitwirez that's sound advice and point taken.  In my case, most everything I have written in the last decade is full-screen / KIOSK style applications, hence the driving force behind the transparency requirement.

@FrankenApps  @grokys so how do I achieve the transparency?  I searched the Avalonia Repo and google for 'WindowTransparencyLevelHint', but came up empty handed.

**Comment by maxkatz6** [comment]
@jtbrower "TransparencyLevelHint" property is available on Window class in preview **0.10**.

**Comment by jtbrower** [comment]
@maxkatz6  NICE!  I was using preview version 3, but once I upgraded to version 5 it was like magic!  Nice work everyone.

**Comment by Mudcatz98** [comment]
I am working with Avalonia version 0.10.13 and trying to achieve a transparent or blurred window background. I can get the desired effect on windows 10 if I follow this [Create modern looking UI example](https://docs.avaloniaui.net/tutorials/music-store-app/creating-a-modern-looking-window). However my primary userbase will be on Linux specifically Raspberry PI's, so I am using the following build options:
````
=> AppBuilder.Configure<App>().With(
                new X11PlatformOptions
                {
                    EnableMultiTouch = true,
                })
                .With(new Win32PlatformOptions
                {
                    EnableMultitouch = true,
                })
                .UsePlatformDetect()
                .LogToTrace()
                .UseReactiveUI();
````

Does anyone have any suggestions on how to achieve transparency or blur in the Linux environment?

**Comment by samsiaw** [comment]
For anyone looking for the answer for a Linux, this worked for me
```xaml
<Window
        ...
        Background="Transparent"
        TransparencyBackgroundFallback="Transparent"
>
<!-- Content -->
</Window>
```

**Comment by 011010101001** [comment]
Dear all, i have problem on wayland, it is not possible to make transparent a window, and another bug is that position it's not working... working perfect in windows, do you have any advice ? thanks so much
