### ISSUE TITLE
Text layout issues (wrapping, text shifting)

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#5854]
**Describe the bug**
After updating to latest master version I've noticed that certain `TextBlock`s in my app behave differently. I've extracted a minimal  repro and compared with WPF.

1. When `TextBlock` bounds are changing one can notice that text position is shifting (visible shaking)
2. It seems in certain cases I'm not able to make `TextBlock` wrap. I'm still investigating this part.

https://user-images.githubusercontent.com/2588062/116754651-67554080-aa09-11eb-9fef-6481b57fb572.mp4

**To Reproduce**

```xaml
<StackPanel Spacing="4">

        <Border BorderBrush="Black" BorderThickness="1" Padding="4" Width="{Binding  #WidthSlider.Value}">
            <TextBlock Text="Long Long Long Long Long Long Long Long"
                       Foreground="Black"
                       TextAlignment="Center" HorizontalAlignment="Stretch" />
        </Border>

        <Slider x:Name="WidthSlider" Value="100" Minimum="0" Maximum="500" />
</StackPanel>
```

**Expected behavior**
Text is not shifting randomly when constraint changes.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version: master

**Comment by Gillibald** [comment]
Thanks for your description. Will test my wrapping fix shortly. I am not sure why the rendering fluctuates so much.

**Comment by Gillibald** [comment]
#5856 should fix the text wrapping

**Comment by mat1jaczyyy** [comment]
when shrinking the width, it seems the two vertical sides of the border do not alternate as in moving a pixel towards the middle in an alternating fashion. the left side will move 2 pixels (one at a time), then the right side will do 2 pixels. this oddity is likely what causes the shake, as the text moves around by 1 pixel because it tries to stay centered.

this might be a separate thing though as it still feels like the text shifts a bit even when a 1px change occurs.

i'm on macOS for reference

https://user-images.githubusercontent.com/13300194/127757639-1ea2b20f-b2d7-455a-bb45-920c3e6472a1.mp4

**Comment by Gillibald** [comment]
WPF uses pixel aligned values for glyph positioning so if we want to achieve the same results we need to do the same.

**Comment by Takoooooo** [comment]
Tested on the latest master,wrapping looks to work ok but shifting is still a problem
